#ifndef RDMA_CLIENT_H
#define RDMA_CLIENT_H

#include "rdma_common.h"

class RdmaClient {
public:
    // IO channel
    struct ibv_comp_channel *io_completion_channel;
    // RDMA_CM channel
    struct rdma_event_channel *cm_event_channel;

private:
    struct rdma_cm_id *cm_client_id;
    struct ibv_pd *client_pd;
    struct ibv_cq *client_cq;
    struct ibv_qp *client_qp;

    struct ibv_qp_init_attr qp_init_attr;

    // Server-Side metadata "recv" from the remote server
    struct RdmaBufferAttr *recv_server_side_metadata_attr;
    // Generated by local rdma API, which is necessary for Server-Side write to
    // client.
    struct RdmaBufferAttr *client_side_metadata_attr;

public:
    // Used for RDMA-write
    SimpleBuffer clientMeta;
    SimpleBuffer serverMeta;

    // Used for RDMA-write
    SimpleBuffer recvReq;
    // Used for RDMA-read
    SimpleBuffer recvRsp;

public:
    RdmaClient()
        : cm_event_channel(nullptr),
          cm_client_id(nullptr),
          client_pd(nullptr),
          io_completion_channel(nullptr),
          client_cq(nullptr),
          client_qp(nullptr) {}

    int client_prepare_connection(struct sockaddr_in *s_addr);
    int client_prepare_recv_buffer_meta();
    int client_connect_to_server();
    int client_xchange_metadata_with_server(SimpleBuffer *pBuf);

    int client_prepare_qp(void);
    // Start:Sending apis for sending data
    // Function: register data mr
    int client_register_data_mr(SimpleBuffer *pBuf, uint32_t size);
    // Function: regular write to remote over RDMA, Only trigger remote write
    // without the memcpy
    int client_remote_memory_write();
    int client_remote_memory_read();
    // Function: regular write to remote over RDMA
    // int client_remote_memory_ops_imm(SimpleBuffer *pBuf, uint32_t size);
    // End:Sending apis for sending data

    int block_check_io_complete();

    int client_disconnect_and_clean(SimpleBuffer *pBuf);
};
#endif // RDMA_CLIENT_H
